version: '3.7'

volumes:
    postgres_data: 
        driver: local

networks:
  external1: 
    name: front-back-network
  external2:
    name: back-mariadb-network

services:
  mailer_service:
    image: arturoalcaniz/mailer-service
    command: bash -c "cd /app/MailerService && bash install.sh"
    environment: 
    # Timezone. Variable from .env file
      - TZ
      - MAILER_CONTAINER_PORT
    tty: true
    stdin_open: true
    container_name: ${MAILER_CONTAINER_NAME}
    networks: 
      - external1
      - external2
